[package]
name = "wechat"
version = "0.1.0"
authors = ["messense <messense@icloud.com>"]
description = "WeChat SDK for Rust"
repository = "https://github.com/messense/wechat-rs"
homepage = "https://github.com/messense/wechat-rs"
readme = "README.md"
keywords = ["wechat", "sdk"]
license = "MIT"

[dependencies]
log = "*"
rust-crypto = "*"
sxd-document = "*"
sxd-xpath = "*"
rand = "*"
time = "*"
byteorder = "*"
rustc-serialize = "*"
hyper = "*"
yup-hyper-mock = "*"

[features]
unstable = []
