[package]
name = "wechat"
version = "0.1.1"
authors = ["messense <messense@icloud.com>"]
description = "WeChat SDK for Rust"
repository = "https://github.com/messense/wechat-rs"
homepage = "https://github.com/messense/wechat-rs"
readme = "README.md"
keywords = ["wechat", "sdk"]
license = "MIT"

[dependencies]
log = "*"
rust-crypto = "*"
sxd-document = "*"
rand = "*"
time = "*"
byteorder = "*"
rustc-serialize = "*"
hyper = "*"
yup-hyper-mock = "*"

[dependencies.sxd-xpath]
git = "https://github.com/shepmaster/sxd-xpath.git"

[dependencies.clippy]
git = "https://github.com/Manishearth/rust-clippy"

[features]
unstable = []
