[package]
name = "wechat"
version = "0.1.1"
authors = ["messense <messense@icloud.com>"]
description = "WeChat SDK for Rust"
repository = "https://github.com/messense/wechat-rs"
homepage = "https://github.com/messense/wechat-rs"
readme = "README.md"
keywords = ["wechat", "sdk"]
license = "MIT"

[dependencies]
log = "*"
url = "*"
sxd-document = "*"
sxd-xpath = "*"
rand = "*"
time = "*"
byteorder = "*"
rustc-serialize = "*"
hyper = "*"
json_macros = "*"
openssl = "*"
multipart = "*"

[dependencies.redis]
git = "https://github.com/mitsuhiko/redis-rs.git"

[features]
unstable = []
